name: Deploy Chrome Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Build & Publish to Chrome Web Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Chrome Extension
        run: yarn build:chrome

      - name: Zip Extension
        run: |
          cd dist_chrome
          zip -r ../extension.zip ./*

      - name: Upload to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5
        with:
          file-path: extension.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: true
